import CurrencyService from './CurrencyService.js';

const currencies = [
  {
    name: 'US Dollar',
    symbol: 'USD',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/us.gif',
  },
  {
    name: 'Euro',
    symbol: 'EUR',
    glyph: '\u20AC',
    flagUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg',
  },
  {
    name: 'Japanese Yen',
    symbol: 'JPY',
    glyph: '\u00A5',
    flagUrl: 'http://www.geonames.org/flags/l/jp.gif',
  },
  {
    name: 'British Pound',
    symbol: 'GBP',
    glyph: '\u00A3',
    flagUrl: 'http://www.geonames.org/flags/l/uk.gif',
  },
  {
    name: 'Australian Dollar',
    symbol: 'AUD',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/au.gif',
  },
  {
    name: 'Canadian Dollar',
    symbol: 'CAD',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/ca.gif',
  },
  {
    name: 'Swiss Franc',
    symbol: 'CHF',
    glyph: '\u0043\u0048\u0046',
    flagUrl: 'http://www.geonames.org/flags/l/ch.gif',
  },
  {
    name: 'Chinese Yuan Renminbi',
    symbol: 'CNY',
    glyph: '\u00A5',
    flagUrl: 'http://www.geonames.org/flags/l/cn.gif',
  },
  {
    name: 'Swedish Krona',
    symbol: 'SEK',
    glyph: '\u006B\u0072',
    flagUrl: 'http://www.geonames.org/flags/l/se.gif',
  },
  {
    name: 'New Zealand Dollar',
    symbol: 'NZD',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/nz.gif',
  },
  {
    name: 'Mexican Peso',
    symbol: 'MXN',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/mx.gif',
  },
  {
    name: 'Singapore Dollar',
    symbol: 'SGD',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/sg.gif',
  },
  {
    name: 'Hong Kong Dollar',
    symbol: 'HKD',
    glyph: '\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/hk.gif',
  },
  {
    name: 'Norwegian Krone',
    symbol: 'NOK',
    glyph: '\u006B\u0072',
    flagUrl: 'http://www.geonames.org/flags/l/no.gif',
  },
  {
    name: 'South Korean Won',
    symbol: 'KRW',
    glyph: '\u20A9',
    flagUrl: 'http://www.geonames.org/flags/l/kr.gif',
  },
  {
    name: 'Turkish Lira',
    symbol: 'TRY',
    glyph: '\u20BA',
    flagUrl: 'http://www.geonames.org/flags/l/tr.gif',
  },
  {
    name: 'Russian Ruble',
    symbol: 'RUB',
    glyph: '\u20BD',
    flagUrl: 'http://www.geonames.org/flags/l/ru.gif',
  },
  {
    name: 'Indian Rupee',
    symbol: 'INR',
    glyph: '\u20B9',
    flagUrl: 'http://www.geonames.org/flags/l/in.gif',
  },
  {
    name: 'Brazilian Real',
    symbol: 'BRL',
    glyph: '\u0052\u0024',
    flagUrl: 'http://www.geonames.org/flags/l/br.gif',
  },
  {
    name: 'South African Rand',
    symbol: 'ZAR',
    glyph: '\u0052',
    flagUrl: 'http://www.geonames.org/flags/l/za.gif',
  },
  {
    name: 'Philippine Peso',
    symbol: 'PHP',
    glyph: '\u20B1',
    flagUrl: 'http://www.geonames.org/flags/l/ph.gif',
  },
  {
    name: 'Czech Koruna',
    symbol: 'CZK',
    glyph: '\u004B\u010D',
    flagUrl: 'http://www.geonames.org/flags/l/cz.gif',
  },
  {
    name: 'Indonesian Rupiah',
    symbol: 'IDR',
    glyph: '\u0052\u0070',
    flagUrl: 'http://www.geonames.org/flags/l/id.gif',
  },
  {
    name: 'Malaysian Ringgit',
    symbol: 'MYR',
    glyph: '\u0052\u004D',
    flagUrl: 'http://www.geonames.org/flags/l/my.gif',
  },
  {
    name: 'Hungarian Forint',
    symbol: 'HUF',
    glyph: '\u0046\u0074',
    flagUrl: 'http://www.geonames.org/flags/l/hu.gif',
  },
  {
    name: 'Icelandic Krona',
    symbol: 'ISK',
    glyph: '\u006B\u0072',
    flagUrl: 'http://www.geonames.org/flags/l/is.gif',
  },
  {
    name: 'Croatian Kuna',
    symbol: 'HRK',
    glyph: '\u006B\u006E',
    flagUrl: 'http://www.geonames.org/flags/l/hr.gif',
  },
  {
    name: 'Bulgarian Lev',
    symbol: 'BGN',
    glyph: '\u043B\u0432',
    flagUrl: 'http://www.geonames.org/flags/l/bg.gif',
  },
  {
    name: 'Romanian Leu',
    symbol: 'RON',
    glyph: '\u006C\u0065\u0069',
    flagUrl: 'http://www.geonames.org/flags/l/ro.gif',
  },
  {
    name: 'Danish Krone',
    symbol: 'DKK',
    glyph: '\u006B\u0072',
    flagUrl: 'http://www.geonames.org/flags/l/dk.gif',
  },
  {
    name: 'Thai Baht',
    symbol: 'THB',
    glyph: '\u0E3F',
    flagUrl: 'http://www.geonames.org/flags/l/th.gif',
  },
  {
    name: 'Polish Zloty',
    symbol: 'PLN',
    glyph: '\u007A\u0142',
    flagUrl: 'http://www.geonames.org/flags/l/pl.gif',
  },
  {
    name: 'Israeli Shekel',
    symbol: 'ILS',
    glyph: '\u20AA',
    flagUrl: 'http://www.geonames.org/flags/l/il.gif',
  },
];

export { currencies, CurrencyService };
